[tox]
envlist = py311,py312,py313,py314
requires = tox>=4.0
isolated_build = True
skipsdist = True

[testenv]
# Install the module in `.` and its `test` extra dependencies from
# setup.cfg.
deps =
    .[test]
changedir = /
# Point directly to the installed package, and do not use `python3 -m pytest`.
# This way we prevent importing the module from the current directory instead
# of the installed package, and failing when it cannot find the shared library.
commands = pytest {envsitepackagesdir}/rocksdb

[testenv:docs]
deps = .[doc]
commands = sphinx-build -W -b html docs docs/_build/html

[pytest]
addopts = --verbose --pyargs
norecursedirs = .tox
